server:
  port: 8081  # Changed port to avoid conflict with other processes

spring:
  application:
    name: eshop-backend

  datasource:
    url: jdbc:mysql://localhost:3306/eshop_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: PHqHB/f*5m8MF3T@
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 15  # Increased max pool size for scalability
      minimum-idle: 5  # Adjusted to have a minimum idle connections for better performance
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
